name: stock_managament_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:

  # firebase
  firebase_core: 
  cloud_firestore:
  firebase_pagination: ^3.1.0
  firebase_storage:
   
  # Core
  get:
  get_storage: 
  restart_app:
  background_sms: ^0.0.4
  permission_handler: ^11.3.1
  path:
  pull_to_refresh: ^2.0.0
  lottie: ^3.1.0
  image_picker:
  cached_network_image: ^3.3.1
   
  # Utils
  flutter_iconly: 
  kartal: ^4.1.0
  cupertino_icons: 
  flutter_screenutil:


  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  #Lints
  very_good_analysis: ^7.0.0  
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/lottie/
    - assets/image/


  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600  
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans-Light.ttf
          weight: 300
        
  uses-material-design: true
