name: stock_managament_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter_lints:
  firebase_core:
  cloud_firestore:
  flutter_iconly:
  flutter_screenutil:
  pull_to_refresh: ^2.0.0
  lottie: ^3.1.0
  get_storage:
  image_picker:
  cached_network_image: ^3.3.1
  # firebase_pagination: ^3.1.0
  firebase_storage:
  firebase_ui_firestore: ^1.6.2
  path:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/lottie/
    - assets/image/

  fonts:
    - family: GilroyBold
      fonts:
        - asset: assets/fonts/Gilroy-Bold.ttf
    - family: GilroySemiBold
      fonts:
        - asset: assets/fonts/Gilroy-SemiBold.ttf
    - family: GilroyMedium
      fonts:
        - asset: assets/fonts/Gilroy-Medium.ttf
    - family: GilroyRegular
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
  uses-material-design: true
  generate: true
