// ignore_for_file: equal_keys_in_map

import 'package:get/get.dart';

class MyTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'tm': {
          'aboutUs': 'Biz barada',
          'add': 'Goş',
          'addAddress': 'Salgy goş',
          'addCart': 'Sebede goş',
          'added': 'Goşuldy',
          'addedSubtitle': 'Sebede haryt goşuldy ',
          'address': 'Öý salgyňyz',
          'agree': 'Tassyklamak',
          'alreadyExist': 'Ulanyjy maglumatlaryňyz bizde ýok. Hasaba al bölümden hasaba girmegiňizi haýýyş edýäris',
          'appColor': 'Programma reňki',
          'appColor1': 'Reňk saýlaň',
          'appColor2': 'Reňk 1',
          'appColor3': 'Reňk 2',
          'appColor4': 'Reňk 3',
          'appObtained': 'Hasap açmak isleseňiz, bu programmany alan adamyňyza ýüz tutmagyňyzy haýyş edýäris',
          'balance': 'Hasap',
          'banner': 'Reklama',
          'brand': 'Brand',
          'brandPP': 'Brand',
          'brands': 'Brendler',
          'call': 'Jaň et',
          'callNumber': 'Telefon Belgilerimiz',
          'cart': 'Sebet',
          'cartEmpty': 'Sebediňiz boş',
          'cartEmptySubtitle': 'Sebediňize hiç zat goşmadyňyz.',
          'cash': 'Nagt',
          'cashSubtitle': 'Sargydy alan wagtyňyz nagt görnüşde hasaplaşmak',
          'categoriesMini': 'Kategoriýalar',
          'category': 'Kategoriýa',
          'changesUpdated': 'Maglumatlar üýtgedildi',
          'chooseTheColor': 'Renk saýlaň : ',
          'chooseTheSize': 'Razmer :',
          'clientAddress': 'Ulanyjy salgysy',
          'clientNumber': 'Belgisi',
          'clientNumber': 'Telefon belgisi',
          'come': 'Geldi',
          'contactInformation': 'Habarlaşmak üçin : ',
          'container': 'Kontainer',
          'copySucces': 'Tassyklandy',
          'copySuccesSubtitle': 'Göçürme ýerine ýetirildi',
          'countProducts': 'Harytlar : ',
          'createdAt': 'Goýulan Senesi : ',
          'creatOrder': 'Sargyt döretmek',
          'creditCart': 'Kart',
          'creditCartSubtitle': 'Sargydy alan wagtyňyz töleg terminaly arkaly hasaplaşmak',
          'data': 'Maglumat :',
          'data1': 'Maşyn ady :',
          'data2': 'Kategoriýa :',
          'data3': 'Görülme sany :',
          'data4': 'Ýüklenme Sany :',
          'data5': 'Goşmaça Maglumat :',
          'date': 'Sene : ',
          'dateOrder': 'Sene',
          'deleteAccount': 'Hasaby pozmak',
          'deleteAccountSubtitle': 'Hasabyňyza degişli hemme maglumatlar pozuldy !',
          'deleteAccountTitle': 'Pozuldy',
          'deleteAddress': 'Salgylarym',
          'deleteAddressTitle': 'Siz hakykatdanda Salgylarymy pozmak isleýärsiňizmi ?',
          'deleteFavProduct': 'Halanlarymy boşat !',
          'deleteFavProductSubtitle': 'Siz hakykatdanam Halanlarymy boşatmakçymy ?',
          'description': 'Düşündiriş',
          'discount': 'Arzanladyş',
          'discountedItems': 'Arzanladyşdaky harytlar',
          'download': 'Ýükle',
          'downloaded': 'Ýüklänlerim',
          'downloadFiles': 'Ýüklemek',
          'doYouWantToDeleteCart': 'Sebedi boşat !',
          'doYouWantToDeleteCartSubtitle': 'Siz hakykatdanam Sebedi boşatmakçymy ?',
          'emptyCart': 'Sebet boş',
          'emptyCartSubtitle': 'Sargyt etmek üçin sebediňizi haryt goşuň',
          'emptyFavS': 'Halan harytlaryňyz sanawy boş.',
          'emptyFavT': 'Halanlarym ýok ',
          'emptyLocations': 'Siziň salgylaryňyz goşulmadyk',
          'error': 'Ýalňyşlyk ýüze çykdy täzeden synanşyň',
          'errorData': 'Girizeň maglumatyňyz ýalňyş !',
          'errorEmpty': 'Tekst gutusy boş bolup bilmez',
          'errorPassword': 'Parol azyndan 6 haryp bolmaly',
          'errorPassword2': 'Parolyňyz ýalňyş',
          'errorPhoneCount': 'Telefon belgiňiz 8 sanly bolmaly.',
          'errorTitle': 'Ýalňyş',
          'favorites': 'Halanlarym',
          'filter': 'Filter',
          'fixMachine': 'Bejeriş Hyzmaty',
          'giveLike': 'Bizi Play marketde bahalandyryň',
          'gramm': 'Gram',
          'hastags': 'Haştaglar',
          'home': 'Baş sahypa',
          'inOurHands': 'Şulary hem halap bilersiňiz',
          'kargoIncluded': 'Kargo mugt',
          'location': 'Haryt salgysy',
          'locations': 'Salgylarym',
          'log_out_title': 'Siz hakykatdanda ulgamdan çykmak isleýärsiňizmi ?',
          'log_out': 'Ulgamdan çyk',
          'login': 'Ulgama gir',
          'loginErrorFillBlanks': 'Boş ýerleri doldurmagyňyzy haýyş edýäris',
          'loginError': 'Ulgama giriň',
          'loginError1': 'Kimdir biri bu giriş maglumatlaryny ulanýar',
          'loginErrorSubtitle': 'Sargyt etmek üçin ulgama giriň',
          'loginErrorSubtitle1': 'Hyzmaty ýerine etmek üçin ulgama giriň',
          'material': 'Materialy',
          'maxPrice': 'Iň gymmat',
          'minPrice': 'Iň arzan',
          'minSumCount': 'Sargydyňyzyň jemi azyndan 50 manat bolmaly',
          'more': 'Goşmaçalar',
          'newItems': 'Täze harytlar',
          'no': 'Ýok',
          'noConnection1': 'Aragatnaşyk ýok',
          'noConnection2': 'Internede baglanyp bolmady.Internet sazlamalaryňyzy barlap gaýtadan synanşyň !',
          'noConnection3': 'Täzeden synanş',
          'noData': 'Maglumat ýüklenmedi, täzeden synanşyň',
          'noData1': 'Wagtlaýynça maglumat ýok !',
          'noFile': 'Hiç hili Faýl ýok. Biz bilen habarlaşyň',
          'noHistoryOrders': 'Hiç hili sargyt etmediňiz',
          'noImage': 'Surat ýok',
          'noMoney': 'Pul ýok',
          'noMoneySubtitle': 'Hyzmaty ýerine ýetirmek üçin Puluňyz ýetenok',
          'noProductSubtitle': 'Haryt gutardy',
          'noProductTitle': 'Gutardy',
          'note': 'Bellik',
          'notification': 'Bildirişler',
          'notWork': 'Işlänok',
          'notWorkSubtitle': 'Waglaýynça hyzmat işlänok',
          'order_status_come': 'Gelenler',
          'order_status_submission': 'Tabşyrylanlar',
          'order_status_wait': 'Sargyt edilenler',
          'order': 'Sargyt',
          'orderAdress': 'Eltip bermek üçin salgyňyz',
          'orderAgreeSubTitle': 'Sargyt eden Suwlaryňyz "BLOK" görnüşinde eltip berilýändir.',
          'orderAgreeTitle': 'Sargyt tassyklaň !',
          'orderComesThatDaySubtitle': 'hepde aralygynda gelýär',
          'orderComesThatDayTitle': 'Zakaz eden harytlaryňyz ',
          'orderComplete': 'Sargyt tassyklandy',
          'orderCompletedTrue': 'Sargydyňyz tassyklandy Siz bilen jaň arkaly habarlaşarlar',
          'orderDeleted': 'Pozuldy',
          'orderDeletedSubtitle': 'Harytlar Sebetden aýyryldy',
          'orderDetails': 'Giňişleýin maglumat',
          'orderName1': 'Garaşylýanlar',
          'orderName2': 'Kabul edilenler',
          'orderName3': 'Ýolda gelýänler ',
          'orderName4': 'Red edilenler',
          'orderProducts': 'Sargyt et',
          'orders': 'Sargytlarym',
          'ordersDeleted': 'Salgylaryňyz pozuldy ',
          'orderSubtitle': 'Sargydyňyz ýerine ýetirmek üçin nobata goýuldy',
          'orderType': 'Sargyt görnüşi',
          'otp': 'Sms kod',
          'otpCheck': 'Otp Werfikasiýa',
          'otpErrorSubtitle': 'Sms koduňyzy ýene bir gezek barlaň',
          'otpErrorTitle': 'SMS kod ýalňyşlygy',
          'otpSubtitle': 'Telefon belgiňize gelen sms kody giriziň',
          'otpTitle': 'Ýazan belgiňize sms arkaly kod ugradylar.',
          'ourDeliveryService': 'Eltip bermek we töleg',
          'package': 'Gaplama',
          'paymentMethod': 'Töleg görnüşi',
          'phoneNumber': 'Telefon belgiňiz',
          'plain': 'Uçar',
          'price': 'Bahasy :',
          'priceProduct': 'Jemi Bahasy : ',
          'priceRange': 'Baha aralygy',
          'product': 'Haryt',
          'productAddToFav': 'Haryt halanlarym goşuldy',
          'productCount': 'Haryt sany',
          'productName': 'Haryt ady',
          'products': 'Harytlar',
          'profil': 'Ulanyjy',
          'quantity': 'Sany',
          'questions': 'Köp soralýan soraglar ?',
          'read': 'Oka',
          'recomendedItems': 'Maslahat berilýän harytlar',
          'referal_Code': 'Referal Kod',
          'referalDesc': 'Bu kod Üsti bilen ulanyjylary çagyryp bilersiňiz ve Pul gazanyp bilersiňiz',
          'referalKod': 'Referal kod',
          'referalKod1': 'Referal kodyňyz',
          'referalKodEarnedMoney': 'Jemi gazanç :',
          'referalKodUsedUser': 'Kody ulanan ulanyjylar',
          'sales': 'Sargytlar',
          'sameProducts': 'Degişli harytlar ',
          'sameProducts': 'Meňzeş harytlar',
          'search': 'Gözleg',
          'select_language': 'Dil saýlaň',
          'selectCityTitle': 'Welaýat saýlaň',
          'selectColor': 'Renk saýlaň !',
          'selectDate': 'Eltip bermeli wagty saýlaň',
          'selectDateTitle': 'Sargyt eltip bermeli wagty :',
          'selectedImage': 'Saýlanan surat',
          'selectMachine': 'Tikin maşyn görnüşi saýlaň',
          'selectSize': 'Razmer saýlaň !',
          'settings': 'Sazlamalar',
          'share': 'Programmany paýlaş',
          'shareUs': 'Programmany paýlaş',
          'shopByBrand': 'Brand boýunça söwda',
          'signIn1': 'Familýaňyz',
          'signIn2': 'Adyňyz',
          'signInDialog': 'Ulgama girmek üçin ulanyjy maglumatlary doly we dogry şekilde dolduruň',
          'signUp': 'Hasaba al',
          'skip': 'Geç',
          'sort': 'Yzygiderlik',
          'sortCreatedAtHighToLow': 'Ilki Täzeler',
          'sortCreatedAtLowToHigh': 'Ilki Köneler',
          'sortDefault': 'Adaty',
          'sortPriceHighToLow': 'Ilki Arzanlan',
          'sortPriceLowToHigh': 'Ilki Gymmatlar',
          'sortViewsASC': 'Köp görülenler',
          'sortViewsDESC': 'Az görülenler',
          'status': 'Ýagdaýy',
          'stockInHand': 'Elimizdaki harytlar',
          'sum': 'Jemi',
          'terms_and_conditions_to_order': 'Hormatly ulanyjy sargyt geçmek üçin ulanyş şertleri we düzgünlerini kabul ediň',
          'terms_and_conditions': 'Ulanyş şertleri we düzgünleri',
          'totalProducts': 'Hemme harytlar',
          'train': 'Ýük maşyn',
          'transferUSB': 'USB geçir',
          'trendingItems': 'Meşhur harytlar',
          'uploadImage': 'Surat ýükle',
          'uploadImageProcessDone': 'Surat ýüklendi !',
          'userInfo': 'Ulanyjy maglumatlary :',
          'userName': 'Ulanyjy ady',
          'userpassword': 'Ulanyjy paroly',
          'versia': 'Wersiýa',
          'videos': 'Gysga wideolar',
          'viewCount': 'Görülme Sany :',
          'waitForSms': 'SMS kod gelýänçä garaşmagyňyzy haýyş edýäris !',
          'waiting': 'Garaşylýar',
          'waitMyMan': 'Garaşyň',
          'waitMyManSubtitle': 'Maglumat ýüklenýänça garaşyň',
          'yes': 'Hawwa',
        },
        'ru': {},
        'en': {},
      };
}
