// ignore_for_file: equal_keys_in_map

import 'package:get/get.dart';

class MyTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'tm': {
          'selectMoreProducts': 'Bir ýa-da birnäçe önümi saýlamagyňyzy haýyş edýäris',
          'done': "Soňy",
          'cannotChangeOrderStatus': "Sargyt ýagdaýyny üýtgedip bilmersiňiz",
          "notHigherThanSumPrice": "Arzanladyş bahasy Jemi bahasyndan ýokary bolup bilmez",
          "createOrder": "Sargyt döretmek",
          'selectProducts': 'Harytlar saýlaň',
          'selectedProducts': 'Saýlanan harytlar',
          'dateOrder': 'Sargyt senesi:',
          'sales': "Sargytlar",
          'errorDontChangeData': "Siz hiç zat üýtgetmediňiz",
          'selectedImage': "Saýlanan surat",
          'totalProducts': 'Hemme harytlar',
          'stockInHand': 'Elimizdaki harytlar',
          'endOFProduct': 'Başga haryt ýok',
          'noProduct': "Harytlar tapylmady",
          'aboutUs': 'Biz barada',
          'add': 'Goş',
          'addAddress': 'Salgy goş',
          'addCart': 'Sebede goş',
          'added': 'Goşuldy',
          'addedSubtitle': 'Sebede haryt goşuldy ',
          'address': 'Öý salgyňyz',
          'agree': 'Tassyklamak',
          'alreadyExist': 'Ulanyjy maglumatlaryňyz bizde ýok. Hasaba al bölümden hasaba girmegiňizi haýýyş edýäris',
          'appColor': 'Programma reňki',
          'appColor1': 'Reňk saýlaň',
          'appColor2': 'Reňk 1',
          'appColor3': 'Reňk 2',
          'appColor4': 'Reňk 3',
          'appObtained': 'Hasap açmak isleseňiz, bu programmany alan adamyňyza ýüz tutmagyňyzy haýyş edýäris',
          'balance': 'Hasap',
          'banner': 'Reklama',
          'brand': 'Brand',
          'brandPP': 'Brand',
          'brands': 'Brendler',
          'call': 'Jaň et',
          'callNumber': 'Telefon Belgilerimiz',
          'cart': 'Sebet',
          'cartEmpty': 'Sebediňiz boş',
          'cartEmptySubtitle': 'Sebediňize hiç zat goşmadyňyz.',
          'cash': 'Nagt',
          'cashSubtitle': 'Sargydy alan wagtyňyz nagt görnüşde hasaplaşmak',
          'categoriesMini': 'Kategoriýalar',
          'category': 'Kategoriýa',
          'changesUpdated': 'Maglumatlar üýtgedildi',
          'chooseTheColor': 'Renk saýlaň : ',
          'chooseTheSize': 'Razmer :',
          'clientAddress': 'Ulanyjy salgysy',
          'clientNumber': 'Belgisi',
          'clientNumber': 'Telefon belgisi',
          'come': 'Geldi',
          'contactInformation': 'Habarlaşmak üçin : ',
          'container': 'Kontainer',
          'copySucces': 'Tassyklandy',
          'copySuccesSubtitle': 'Göçürme ýerine ýetirildi',
          'countProducts': 'Harytlar : ',
          'creatOrder': 'Sargyt döretmek',
          'date': 'Sene : ',
          'description': 'Düşündiriş',
          'discount': 'Arzanladyş',
          'download': 'Ýükle',
          'downloaded': 'Ýüklänlerim',
          'downloadFiles': 'Ýüklemek',
          'doYouWantToDeleteCart': 'Sebedi boşat !',
          'doYouWantToDeleteCartSubtitle': 'Siz hakykatdanam Sebedi boşatmakçymy ?',
          'emptyCart': 'Sebet boş',
          'error': 'Ýalňyşlyk ýüze çykdy täzeden synanşyň',
          'errorData': 'Girizeň maglumatyňyz ýalňyş !',
          'errorEmpty': 'Tekst gutusy boş bolup bilmez',
          'errorPassword': 'Parol azyndan 6 haryp bolmaly',
          'errorPassword2': 'Parolyňyz ýalňyş',
          'errorPhoneCount': 'Telefon belgiňiz 8 sanly bolmaly.',
          'errorTitle': 'Ýalňyş',
          'favorites': 'Halanlarym',
          'filter': 'Filter',
          'fixMachine': 'Bejeriş Hyzmaty',
          'giveLike': 'Bizi Play marketde bahalandyryň',
          'gramm': 'Gram',
          'hastags': 'Haştaglar',
          'home': 'Baş sahypa',
          'inOurHands': 'Şulary hem halap bilersiňiz',
          'kargoIncluded': 'Kargo mugt',
          'location': 'Haryt salgysy',
          'locations': 'Salgylarym',
          'log_out_title': 'Siz hakykatdanda ulgamdan çykmak isleýärsiňizmi ?',
          'log_out': 'Ulgamdan çyk',
          'login': 'Ulgama gir',
          'loginErrorFillBlanks': 'Boş ýerleri doldurmagyňyzy haýyş edýäris',
          'loginError': 'Ulgama giriň',
          'loginError1': 'Kimdir biri bu giriş maglumatlaryny ulanýar',
          'loginErrorSubtitle': 'Sargyt etmek üçin ulgama giriň',
          'loginErrorSubtitle1': 'Hyzmaty ýerine etmek üçin ulgama giriň',
          'material': 'Materialy',
          'maxPrice': 'Iň gymmat',
          'minPrice': 'Iň arzan',
          'minSumCount': 'Sargydyňyzyň jemi azyndan 50 manat bolmaly',
          'more': 'Goşmaçalar',
          'no': 'Ýok',
          'noConnection1': 'Aragatnaşyk ýok',
          'noConnection2': 'Internede baglanyp bolmady.Internet sazlamalaryňyzy barlap gaýtadan synanşyň !',
          'noConnection3': 'Täzeden synanş',
          'noData': 'Maglumat ýüklenmedi, täzeden synanşyň',
          'noData1': 'Wagtlaýynça maglumat ýok !',
          'noFile': 'Hiç hili Faýl ýok. Biz bilen habarlaşyň',
          'noHistoryOrders': 'Hiç hili sargyt etmediňiz',
          'noImage': 'Surat ýok',
          'noMoney': 'Pul ýok',
          'noMoneySubtitle': 'Hyzmaty ýerine ýetirmek üçin Puluňyz ýetenok',
          'noProductTitle': 'Gutardy',
          'note': 'Bellik',
          'notification': 'Bildirişler',
          'notWork': 'Işlänok',
          'notWorkSubtitle': 'Waglaýynça hyzmat işlänok',
          'order_status_come': 'Gelenler',
          'order_status_submission': 'Tabşyrylanlar',
          'order_status_wait': 'Sargyt edilenler',
          'order': 'Sargyt',
          'orders': 'Sargytlarym',
          'ordersDeleted': 'Salgylaryňyz pozuldy ',
          'orderSubtitle': 'Sargydyňyz ýerine ýetirmek üçin nobata goýuldy',
          'orderType': 'Sargyt görnüşi',
          'otp': 'Sms kod',
          'otpCheck': 'Otp Werfikasiýa',
          'otpErrorSubtitle': 'Sms koduňyzy ýene bir gezek barlaň',
          'otpErrorTitle': 'SMS kod ýalňyşlygy',
          'otpSubtitle': 'Telefon belgiňize gelen sms kody giriziň',
          'otpTitle': 'Ýazan belgiňize sms arkaly kod ugradylar.',
          'ourDeliveryService': 'Eltip bermek we töleg',
          'package': 'Gaplama',
          'paymentMethod': 'Töleg görnüşi',
          'phoneNumber': 'Telefon belgiňiz',
          'plain': 'Uçar',
          'price': 'Bahasy :',
          'priceProduct': 'Jemi Bahasy : ',
          'priceRange': 'Baha aralygy',
          'product': 'Haryt',
          'productAddToFav': 'Haryt halanlarym goşuldy',
          'productCount': 'Haryt sany',
          'productName': 'Haryt ady',
          'products': 'Harytlar',
          'profil': 'Ulanyjy',
          'quantity': 'Sany',
          'questions': 'Köp soralýan soraglar ?',
          'read': 'Oka',
          'referal_Code': 'Referal Kod',
          'referalDesc': 'Bu kod Üsti bilen ulanyjylary çagyryp bilersiňiz ve Pul gazanyp bilersiňiz',
          'referalKod': 'Referal kod',
          'referalKod1': 'Referal kodyňyz',
          'referalKodEarnedMoney': 'Jemi gazanç :',
          'referalKodUsedUser': 'Kody ulanan ulanyjylar',
          'search': 'Gözleg',
          'settings': 'Sazlamalar',
          'signInDialog': 'Ulgama girmek üçin ulanyjy maglumatlary doly we dogry şekilde dolduruň',
          'status': 'Ýagdaýy',
          'sum': 'Jemi',
          'uploadImage': 'Surat ýükle',
          'uploadImageProcessDone': 'Surat ýüklendi !',
          'userInfo': 'Ulanyjy maglumatlary :',
          'userName': 'Ulanyjy ady',
          'userpassword': 'Ulanyjy paroly',
          'versia': 'Wersiýa',
          'waiting': 'Garaşylýar',
          'waitMyMan': 'Garaşyň',
          'waitMyManSubtitle': 'Maglumat ýüklenýänça garaşyň',
          'yes': 'Hawwa',
        },
        'ru': {},
        'en': {},
      };
}
